Fix payments service db config and update staging/dynamic certs

diff --git a/codefresh/templates/configmaps/certs-cm.yaml b/codefresh/templates/configmaps/certs-cm.yaml
--- a/codefresh/templates/configmaps/certs-cm.yaml
+++ b/codefresh/templates/configmaps/certs-cm.yaml
@@ -28,8 +28,11 @@ data:
     openssl req -new -key tls.key -out server.csr -subj "/CN={{ .Values.global.appUrl }}"
     openssl x509 -req -days 365 -in server.csr -signkey tls.key -out tls.crt
 
-    kubectl create secret tls {{ template "fullname" . }}-star-selfsigned --cert=tls.crt --key=tls.key
-    kubectl label secret {{ template "fullname" . }}-star-selfsigned app={{ template "fullname" . }}
+    secretName={{ template "fullname" . }}-star-selfsigned
+    if ! kubectl get secret $secretName; then
+      kubectl create secret tls $secretName --cert=tls.crt --key=tls.key
+      kubectl label secret $secretName app={{ template "fullname" . }}
+    fi
 {{- end }}
   gen-runtime-certs: |
     #!/bin/sh
@@ -73,9 +76,13 @@ data:
     cp -v $SERVER_PEM $CLIENT_CERT
     cp -v $SERVER_KEY $CLIENT_KEY
 
-    kubectl create secret generic {{ template "fullname" . }}-cf-certs \
-      --from-file=$CA_PEM \
-      --from-file=$CLIENT_KEY \
-      --from-file=$CLIENT_CERT || err "Failed storing the generated certificates in Kubernetes!"
+    secretName={{ template "fullname" . }}-cf-certs
 
-    kubectl label secret {{ template "fullname" . }}-cf-certs app={{ template "fullname" . }}
+    if ! kubectl get secret $secretName; then
+      kubectl create secret generic {{ template "fullname" . }}-cf-certs \
+        --from-file=$CA_PEM \
+        --from-file=$CLIENT_KEY \
+        --from-file=$CLIENT_CERT || err "Failed storing the generated certificates in Kubernetes!"
+
+      kubectl label secret $secretName app={{ template "fullname" . }}
+    fi
